from .base import BaseParser
from .banks.raiffeisen import RaiffeisenParser
from .banks.fio import FioParser
from .banks.ceska_sporitelna import CeskaSporitelnaParser
from .banks.revolut import RevolutParser
from .banks.czech_universal import CzechUniversalParser
from .banks.unicredit import UniCreditParser
from .banks.mbank import MBankParser
from .banks.csob import CsobParser
from .generic import GenericParser
from .detector import detect_bank
